# Generated by Django 3.2.16 on 2023-11-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qestion',
            new_name='question',
        ),
    ]
